// ADR-0047 (accepts RFC-022) — brain export projections: `vfkb export agents-md` +
// `vfkb export okf`. One projection core, two render targets. The output is a pure
// function of the brain's content: the "as-of" moment is max(entry.updated) — never
// the wall clock — the tree rewrite never reads previously emitted output, ordering
// is total (heuristicCompare + id tiebreak), and filenames derive from the entry id
// alone. The ADR-0046 ratchet is the publish filter for BOTH targets.

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import {
  deriveConstitution,
  effectiveStatus,
  heuristicCompare,
  isDecisionFamily,
  isInjectable,
  readAll,
  supersededIds,
} from './engine.js';
import { defaultProject, isTombstone, readContextSpine, readRecords } from './storage.js';
import type { StoredRecord } from './storage.js';
import { normalizeEntry } from './validate.js';
import type { EntryType, KnowledgeEntry } from './types.js';

// Stamped into every emitted file; the scoped sweep deletes ONLY files carrying it,
// and refuses a non-empty target that has none (a one-flag `--out` mistake must
// hard-fail, not destroy hand-written content).
export const GENERATED_MARKER = 'generated by vfkb export';
// The sweep/guard check is LINE-ANCHORED to the emitted shape — a hand-written doc
// that merely QUOTES the marker phrase mid-sentence (RFC-022 itself does) must
// neither defeat the refusal nor enter the deletion set.
const MARKER_LINE_RE = /^<!-- generated by vfkb export /m;
// Export-sized budget for the AGENTS.md digest (a cold-agent digest, not a dump).
export const EXPORT_BUDGET_CHARS = 40_000;

export interface ExportOpts {
  out?: string;
  project?: string;
  budget?: number;
}

const TYPE_DIR: Record<EntryType, string> = {
  fact: 'facts',
  gotcha: 'gotchas',
  pattern: 'patterns',
  decision: 'decisions',
  link: 'links',
};

// --- the shared projection core -------------------------------------------------

// asOf = max(entry.updated) across the live brain — the projection's clock.
function asOfDate(entries: KnowledgeEntry[]): string {
  let max = '';
  for (const e of entries) if (e.updated > max) max = e.updated;
  return (max || '0000-01-01').slice(0, 10);
}

// Total, stable ordering: heuristicCompare (tier → trust → recency) with an explicit
// id tiebreak — same-millisecond writes exist, and V8 sort stability is not a contract.
function exportCompare(a: KnowledgeEntry, b: KnowledgeEntry): number {
  return heuristicCompare(a, b) || (a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
}

// The four-clause export predicate (ADR-0046's ratchet, RFC-022 §Target 2).
// isInjectable evaluated at asOf carries clauses 2–4 (superseded/deprecated,
// zone ≠ archive, stale/expired provenance, validity window open at asOf); the
// ratchet adds verified-only and accepted-only-for-decisions on top. It is
// deliberately STRICTER than live injection (ADR-0005 keeps unverified-labelled
// injection for sessions; publishing is a different trust boundary).
function exportEligible(e: KnowledgeEntry, asOf: string, superseded: Set<string>): boolean {
  if (!isInjectable(e, asOf, superseded)) return false;
  if (e.provenance.status !== 'verified') return false;
  if (isDecisionFamily(e.type) && effectiveStatus(e, superseded) !== 'accepted') return false;
  return true;
}

// Record-level publish-grade check for the log.md derivation: was THIS historical
// record's state publish-grade on its own terms? No superseded set (supersession is
// a current-state fact, not a property of the old record) and no validity clause
// (expiry is how an entry LEAVES the published view, which is what the log records).
function recordWasPublishGrade(e: KnowledgeEntry): boolean {
  if (e.zone === 'archive') return false;
  if (e.provenance.status !== 'verified') return false;
  if (isDecisionFamily(e.type) && e.status !== 'accepted') return false;
  return true;
}

function firstSentence(text: string, max = 120): string {
  const oneLine = text.split('\n')[0];
  const dot = oneLine.indexOf('. ');
  const s = dot > 0 ? oneLine.slice(0, dot + 1) : oneLine;
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

const yamlStr = (s: string) => JSON.stringify(s);

function projectionInputs() {
  const all = readAll();
  const superseded = supersededIds(all);
  const asOf = asOfDate(all);
  const eligible = all.filter((e) => exportEligible(e, asOf, superseded)).sort(exportCompare);
  return { all, superseded, asOf, eligible };
}

// --- the scoped sweep ------------------------------------------------------------

function listFiles(dir: string): string[] {
  const out: string[] = [];
  const walk = (d: string) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else out.push(p);
    }
  };
  walk(dir);
  return out;
}

function isGenerated(path: string): boolean {
  if (!path.endsWith('.md')) return false;
  try {
    return MARKER_LINE_RE.test(readFileSync(path, 'utf8'));
  } catch {
    return false;
  }
}

// Rewrite-preparation for the OKF tree: delete ONLY generated-marker files (then any
// dirs left empty); refuse outright when a non-empty target carries no generated
// files at all — that is a wrong `--out`, not a previous export.
function prepareTree(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
    return;
  }
  const files = listFiles(dir);
  if (files.length === 0) return;
  const generated = files.filter(isGenerated);
  if (generated.length === 0) {
    throw new Error(
      `vfkb export: refusing to write into non-empty ${dir} — it contains no generated files; point --out at an empty directory or a previous export target`,
    );
  }
  for (const f of generated) rmSync(f);
  // remove dirs the sweep emptied (bottom-up), leaving any dir still holding foreign files
  const dirs: string[] = [];
  const collect = (d: string) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) {
        collect(p);
        dirs.push(p);
      }
    }
  };
  collect(dir);
  for (const d of dirs.reverse()) {
    if (readdirSync(d).length === 0) rmSync(d, { recursive: true });
  }
}

// --- target 1: AGENTS.md ----------------------------------------------------------

export function exportAgentsMd(opts: ExportOpts = {}): { path: string } {
  const { superseded, asOf, eligible } = projectionInputs();
  const project = opts.project ?? defaultProject();
  const budget = opts.budget ?? EXPORT_BUDGET_CHARS;
  const out = opts.out ?? join(process.cwd(), 'AGENTS.md');

  if (existsSync(out) && !MARKER_LINE_RE.test(readFileSync(out, 'utf8'))) {
    throw new Error(
      `vfkb export: refusing to overwrite ${out} — it is not a previous export (no generated marker)`,
    );
  }

  // Constitution leads (ADR-0008) — but the ratchet still binds: a constitutional
  // decision below the publish bar does not ship.
  const constitution = deriveConstitution().filter((e) => exportEligible(e, asOf, superseded));
  const constitutionalIds = new Set(constitution.map((c) => c.id));
  const knowledge = eligible.filter((e) => !constitutionalIds.has(e.id));

  let head =
    `<!-- ${GENERATED_MARKER} agents-md; regenerate with \`vfkb export agents-md\`, do not hand-edit (as-of ${asOf}) -->\n` +
    `# ${project} — agent context (generated from the vfkb brain)\n\n`;

  if (constitution.length > 0) {
    head += '## Constitution (always applies)\n';
    for (const c of constitution) {
      const n = typeof c.adr_no === 'number' ? `ADR-${String(c.adr_no).padStart(4, '0')} ` : '';
      head += `- [${n}constitutional] ${c.text}\n`;
    }
    head += '\n';
  }

  // Export-variant map: counts over the PUBLISHED subset only (unpublished entries
  // leak neither counts nor tag strings), no live-session affordances.
  const published = [...constitution, ...knowledge];
  const byType = new Map<EntryType, number>();
  const tagCounts = new Map<string, number>();
  let accepted = 0;
  for (const e of published) {
    byType.set(e.type, (byType.get(e.type) ?? 0) + 1);
    for (const t of e.tags) tagCounts.set(t, (tagCounts.get(t) ?? 0) + 1);
    if (isDecisionFamily(e.type)) accepted++;
  }
  const typesLine = [...byType.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([t, n]) => `${t} ${n}`)
    .join(' · ');
  const topTags = [...tagCounts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 8)
    .map(([t, n]) => `${t}(${n})`)
    .join(' ');
  head += '## Map\n';
  head += `${published.length} published entr${published.length === 1 ? 'y' : 'ies'}${typesLine ? ` · ${typesLine}` : ''}\n`;
  head += `decisions: ${accepted} accepted (${constitution.length} constitutional)\n`;
  if (topTags) head += `top tags: ${topTags}\n`;
  head += '\n';

  const spine = readContextSpine();
  if (spine) head += `## Context (authored spine)\n${spine.trim()}\n\n`;

  head += '## Knowledge (verified, published)\n';
  let body = '';
  let dropped = 0;
  for (const e of knowledge) {
    const line = `- [${e.type}] ${e.text}\n`;
    if (head.length + body.length + line.length > budget) {
      dropped++;
      continue;
    }
    body += line;
  }
  if (dropped > 0) body += `<!-- ${dropped} entries omitted for the ${budget}-char budget -->\n`;

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, head + body);
  return { path: out };
}

// --- target 2: the OKF v0.1 bundle -------------------------------------------------

function okfDoc(e: KnowledgeEntry, asOf: string, exportedDirs: Map<string, string>): string {
  const title = firstSentence(e.text);
  const fm: string[] = ['---'];
  fm.push(`type: ${e.type}`);
  fm.push(`title: ${yamlStr(title)}`);
  fm.push(`description: ${yamlStr(title)}`);
  if (e.tags.length > 0) fm.push(`tags: ${JSON.stringify(e.tags)}`);
  fm.push(`timestamp: ${e.updated}`);
  if (e.type === 'link') {
    const url = /https?:\/\/[^\s)"'\]]+/.exec(e.text)?.[0]?.replace(/[.,;:]+$/, '');
    if (url) fm.push(`resource: ${yamlStr(url)}`); // never fabricated — only a real URL
  }
  fm.push(`generated_by: vfkb export okf`);
  fm.push('---');

  let body = `<!-- ${GENERATED_MARKER} okf; regenerate with \`vfkb export okf\`, do not hand-edit (as-of ${asOf}) -->\n\n`;
  body += `${e.text.trim()}\n`;

  const citations: string[] = [];
  for (const rel of e.refs?.related ?? []) {
    const dir = exportedDirs.get(rel);
    citations.push(dir ? `- [/${dir}/${rel}.md](/${dir}/${rel}.md)` : `- related entry ${rel}`);
  }
  for (const f of e.refs?.files ?? []) citations.push(`- ${f}`);
  if (e.refs?.commit) citations.push(`- commit ${e.refs.commit}`);
  if (citations.length > 0) body += `\n# Citations\n${citations.join('\n')}\n`;

  return `${fm.join('\n')}\n${body}`;
}

// log.md — a pure function of the brain's RAW record history (readRecords-level).
// The materialized LWW view cannot prove an entry was ever publish-grade (a
// verified→stale restamp shows only `stale`; a tombstoned entry vanishes), so the
// departure set is: some raw record was publish-grade AND the id is not exported now.
function deriveLog(eligibleIds: Set<string>, records: StoredRecord[], live: KnowledgeEntry[]): string[] {
  const byId = new Map<string, StoredRecord[]>();
  for (const r of records) {
    if (!r || typeof (r as { id?: unknown }).id !== 'string') continue;
    const list = byId.get(r.id) ?? [];
    list.push(r);
    byId.set(r.id, list);
  }
  const liveById = new Map(live.map((e) => [e.id, e]));
  const successorOf = new Map<string, KnowledgeEntry>();
  for (const e of live) if (e.refs?.supersedes) successorOf.set(e.refs.supersedes, e);

  const departures: Array<{ at: string; id: string; line: string }> = [];
  for (const [id, recs] of byId) {
    if (eligibleIds.has(id)) continue;
    // earliest (min-updated) publish-grade record — set-deterministic, no reliance
    // on file order even across hypothetical record reorderings
    let grade: KnowledgeEntry | undefined;
    for (const r of recs) {
      if (isTombstone(r)) continue;
      const n = normalizeEntry(r);
      if (n.ok && recordWasPublishGrade(n.entry) && (!grade || n.entry.updated < grade.updated)) {
        grade = n.entry;
      }
    }
    if (!grade) continue; // never publish-grade → not a departure

    const cur = liveById.get(id);
    let at: string;
    let reason: string;
    if (!cur) {
      const tomb = recs.filter(isTombstone).sort((a, b) => b.updated.localeCompare(a.updated))[0];
      at = tomb?.updated ?? grade.updated;
      reason = 'deleted (tombstoned)';
    } else if (successorOf.has(id)) {
      at = successorOf.get(id)!.updated;
      reason = `superseded by ${successorOf.get(id)!.id}`;
    } else if (cur.provenance.status !== 'verified') {
      at = cur.updated;
      reason = `provenance re-stamped ${cur.provenance.status}`;
    } else if (cur.zone === 'archive') {
      at = cur.updated;
      reason = 'archived';
    } else if (cur.status === 'deprecated') {
      at = cur.updated;
      reason = 'deprecated';
    } else if (cur.validity.valid_until) {
      at = cur.validity.valid_until;
      reason = `validity window closed ${cur.validity.valid_until.slice(0, 10)}`;
    } else {
      at = cur.updated;
      reason = 'no longer eligible';
    }
    departures.push({
      at,
      id,
      line: `- ${at.slice(0, 10)} — ${id} [${grade.type}] ${yamlStr(firstSentence(grade.text, 80))} — ${reason}`,
    });
  }
  departures.sort((a, b) => a.at.localeCompare(b.at) || (a.id < b.id ? -1 : 1));
  return departures.map((d) => d.line);
}

export function exportOkf(opts: ExportOpts = {}): { dir: string; files: string[] } {
  const { superseded, asOf, eligible } = projectionInputs();
  const project = opts.project ?? defaultProject();
  const dir = opts.out ?? join(process.cwd(), '.okf');
  prepareTree(dir);

  const marker = `<!-- ${GENERATED_MARKER} okf; regenerate with \`vfkb export okf\`, do not hand-edit (as-of ${asOf}) -->`;
  const files: string[] = [];
  const write = (rel: string, content: string) => {
    const p = join(dir, rel);
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
    files.push(rel);
  };

  const exportedDirs = new Map(eligible.map((e) => [e.id, TYPE_DIR[e.type]]));
  const byDir = new Map<string, KnowledgeEntry[]>();
  for (const e of eligible) {
    const d = TYPE_DIR[e.type];
    const list = byDir.get(d) ?? [];
    list.push(e);
    byDir.set(d, list);
  }

  for (const [d, entries] of [...byDir.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    for (const e of entries) write(`${d}/${e.id}.md`, okfDoc(e, asOf, exportedDirs));
    const lines = entries.map((e) => `- [${firstSentence(e.text, 80).replace(/\]/g, '\\]')}](/${d}/${e.id}.md)`);
    write(`${d}/index.md`, `${marker}\n\n# ${d}\n\n${lines.join('\n')}\n`);
  }

  const rootLines = [...byDir.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([d, entries]) => `- [${d}/](/${d}/index.md) — ${entries.length} document${entries.length === 1 ? '' : 's'}`);
  write(
    'index.md',
    `${marker}\n\n# ${project} — OKF bundle (generated from the vfkb brain, as-of ${asOf})\n\n` +
      `${rootLines.join('\n') || '(no published entries)'}\n\n` +
      `See [log.md](/log.md) for entries that have left the published view.\n`,
  );

  const logLines = deriveLog(new Set(eligible.map((e) => e.id)), readRecords(), readAll());
  write(
    'log.md',
    `${marker}\n\n# log — departures from the published view\n\n` +
      `${logLines.join('\n') || '(none)'}\n`,
  );

  return { dir, files: files.sort() };
}

// CLI dispatch (`vfkb export <target> [--out <path>]`).
export function runExport(target: string | undefined, opts: ExportOpts = {}): string {
  if (target === 'agents-md') return `wrote ${exportAgentsMd(opts).path}`;
  if (target === 'okf') {
    const r = exportOkf(opts);
    return `wrote ${r.files.length} files → ${r.dir}`;
  }
  throw new Error('usage: vfkb export <agents-md|okf> [--out <path>]');
}
