// FR-1 (ADR-0030) — `vfkb init [project]`: idempotently scaffold a CONSUMER repo
// so a session there runs on vfkb automatically. Writes the auto-layer wiring in
// the portable `$VFKB_HOME` form (FR-2), the .gitignore stanza, an empty brain,
// and a parameterized "how we track work HERE" snippet. Re-running is safe: each
// piece is created-if-absent / merged-if-present, and a brain is NEVER clobbered.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { writeManifest } from './manifest.js';

export type InitAction = 'created' | 'updated' | 'skipped';
export interface InitChange {
  path: string;
  action: InitAction;
}

const AGENTS_MARKER = '<!-- vfkb:how-we-track-work -->';
const BOOTSTRAP_REL = '.vfkb/bin/bootstrap.mjs';

// --- pi face wiring (ADR-0066) -------------------------------------------------
// The pi package is git-only for milestone 1 (ADR-0066 §2). A project-scoped
// `.pi/settings.json` is team-shareable and pi AUTO-INSTALLS missing packages at
// startup, so this one line is the whole delivery path for a teammate.
const PI_PACKAGE_SOURCE = 'git:github.com/vilosource/vfkb-pi-package';

// NOTE — deliberately NO `.vfkb/mcp.json` here, and the reason is the whole point of
// ADR-0066. The bridge is configured by $VFKB_MCP_CONFIG, and pi cannot set env vars
// (no `env` key in its settings schema — observed live on 0.73.1, brain gotcha
// 0f1441f9bff2). The fix lives in the PACKAGE: a wrapper extension, listed before the
// bridge in the package manifest, resolves the vendored MCP server relative to its own
// location and points the bridge at it. That is what makes `pi install` self-sufficient.
//
// Writing an mcp.json here pointing at `.vfkb/bin/bootstrap.mjs` would have re-imposed
// $VFKB_BUNDLE_DIR — the old fallback mechanism (ADR-0030) the package exists to retire.
// A consumer may still drop a `.vfkb/mcp.json` by hand to override or add servers; the
// wrapper honours it first and `vfkb doctor` validates it. It is an override, not wiring.

// The wiring entry-point is a COMMITTED, RELATIVE bootstrap (ADR-0031) — always
// resolvable in any clone. The bootstrap resolves the real engine via $VFKB_HOME
// at runtime and degrades gracefully (a clear banner, never a crash/blocked write)
// when it is unset. This also avoids depending on `${VFKB_HOME}` arg-expansion.
function mcpConfig(project: string) {
  return {
    command: 'node',
    args: [BOOTSTRAP_REL, 'mcp'],
    env: { VFKB_DATA_DIR: '.vfkb', VFKB_PROJECT: project },
  };
}

// Anchor hook paths to the project root Claude Code injects into the hook env
// ($CLAUDE_PROJECT_DIR), defaulting to the CWD-relative form when it is unset so the
// wiring never regresses. Hooks run in the SESSION's cwd — which is NOT guaranteed to
// be the repo root (it follows `cd`) — so the bare-relative `node .vfkb/bin/bootstrap.mjs`
// threw MODULE_NOT_FOUND the moment a session cd'd out of the root (issue #22, ADR-0035).
// $CLAUDE_PROJECT_DIR is CWD-independent (empirically verified) and hook commands are
// shell-run, so `${VAR:-.}` parameter-expansion resolves. (The MCP server in .mcp.json
// stays relative — it is spawned once at session start with cwd=root, not re-invoked.)
function hookCommand(project: string, sub: string): string {
  const root = '${CLAUDE_PROJECT_DIR:-.}';
  return `VFKB_DATA_DIR=${root}/.vfkb VFKB_PROJECT=${project} node ${root}/${BOOTSTRAP_REL} cli hook ${sub}`;
}

// The bootstrap source, written verbatim into the consumer repo. Self-contained
// (no engine import — it must run even when the engine is unresolvable). Bump
// BOOTSTRAP_VERSION on a change so `vfkb init` upgrades an older one in place.
const BOOTSTRAP_VERSION = 2;
const BOOTSTRAP_SRC = `#!/usr/bin/env node
// vfkb engine bootstrap (ADR-0031) — vfkb-bootstrap-version: ${BOOTSTRAP_VERSION}
// Committed at a RELATIVE path so it is always resolvable. Resolves the real
// engine via $VFKB_BUNDLE_DIR at runtime; degrades GRACEFULLY (clear, actionable
// message; never breaks the session) when it is unset or the bundles are missing.
// DO NOT hand-edit — regenerated by \`vfkb init\`.
import { existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { join } from 'node:path';

const mode = process.argv[2] === 'mcp' ? 'mcp' : 'cli';
const passthrough = process.argv.slice(3);
// VFKB_BUNDLE_DIR is canonical; VFKB_HOME is a kept-working deprecated alias.
const home = process.env.VFKB_BUNDLE_DIR || process.env.VFKB_HOME;
const engine = mode === 'mcp' ? 'vfkb-mcp.mjs' : 'vfkb.mjs';
const enginePath = home ? join(home, engine) : '';

const FIX =
  'vfkb is INACTIVE: VFKB_BUNDLE_DIR is not set (or its bundles are missing). ' +
  'Fix: build the bundles in the vfkb repo (\\\`npm run build:bundles\\\`) and ' +
  '\\\`export VFKB_BUNDLE_DIR=/path/to/vfkb/dist/bundles\\\` (see docs/CONSUMER-ONBOARDING.md). ' +
  'Then run \\\`vfkb doctor\\\` to verify.';

if (!home || !existsSync(enginePath)) {
  // SessionStart: inform the user via the injection channel (a valid hook payload).
  if (mode === 'cli' && passthrough[1] === 'session-start') {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: { hookEventName: 'SessionStart', additionalContext: '⚠️ ' + FIX },
    }));
    process.exit(0);
  }
  // PreToolUse / Stop / MCP: note it, but NEVER block writes or crash the turn.
  process.stderr.write('vfkb-bootstrap: ' + FIX + '\\n');
  process.exit(0);
}

// Resolved — run the real engine transparently (stdio passed through).
const r = spawnSync('node', [enginePath, ...passthrough], { stdio: 'inherit' });
process.exit(r.status == null ? 0 : r.status);
`;

function settingsHooks(project: string) {
  return {
    SessionStart: [{ hooks: [{ type: 'command', command: hookCommand(project, 'session-start') }] }],
    PreToolUse: [
      { matcher: 'Write|Edit|MultiEdit', hooks: [{ type: 'command', command: hookCommand(project, 'pre-tool-use') }] },
    ],
    Stop: [{ hooks: [{ type: 'command', command: hookCommand(project, 'stop') }] }],
    SessionEnd: [{ hooks: [{ type: 'command', command: hookCommand(project, 'session-end') }] }],
  };
}

function agentsSnippet(project: string): string {
  return `${AGENTS_MARKER}
## How we track work HERE — vfkb

This repo uses **vfkb** as its knowledge substrate (project \`${project}\`). Knowledge is recorded
**deliberately, through the engine** — never by hand-editing \`.vfkb/\` (a PreToolUse hook gates that).

- **Session start** injects the resume digest + knowledge bundle automatically (SessionStart hook).
- **Record knowledge** with the \`mcp__vfkb__kb_add\` tool (or \`node .vfkb/bin/bootstrap.mjs cli add …\`):
  \`decision\`, \`fact\`, \`gotcha\`, \`pattern\`, \`link\` — put a decision's rationale in its text.
  **Capture load-bearing decisions immediately — don't defer.**
- Committed: \`.vfkb/entries.jsonl\`, \`.vfkb/manifest.json\` (the ADR-0030 engine stamp —
  **never gitignore \`manifest.json\`**), \`.vfkb/bin/\`, and \`.pi/settings.json\`.
  Derived/gitignored: \`.vfkb/index-meta.json\`, \`.vfkb/.sessions/\`, \`.vfkb/.signals/\`,
  \`.vfkb/.journal/\`, \`.vfkb/.lock\`, and \`.pi/git/\` (pi's package clone).
- **Works in [pi](https://pi.dev) too** (ADR-0066): \`.pi/settings.json\` loads the \`vfkb-pi-package\`
  and pi auto-installs it at startup, so a teammate's clone wires itself. The package vendors its
  own engine and finds this brain by itself — there is **no \`.vfkb/mcp.json\` to write, and its
  absence is normal**. (You may add one to override or add MCP servers; \`vfkb doctor\` validates it
  if present. Do NOT hand-write one pointing at \`.vfkb/bin/bootstrap.mjs\` — that re-imposes the
  per-machine \`$VFKB_BUNDLE_DIR\` the package exists to retire, and shadows its bundled server.)
  Run \`vfkb doctor\` to check the wiring.

Two env vars: **\`VFKB_DATA_DIR\`** = this repo's brain (\`.vfkb\`, set by the wiring) · **\`VFKB_BUNDLE_DIR\`**
= the shared vfkb engine bundles — set it once per machine, e.g. \`export VFKB_BUNDLE_DIR=/path/to/vfkb/dist/bundles\`.
If it is unset, a session-start banner tells you; run \`vfkb doctor\` to check.
`;
}

function readJson(path: string): any | undefined {
  if (!existsSync(path)) return undefined;
  try {
    return JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    return undefined;
  }
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, JSON.stringify(value, null, 2) + '\n');
}

function eventHasVfkb(arr: unknown): boolean {
  return JSON.stringify(arr ?? '').includes(BOOTSTRAP_REL);
}

export function initProject(root: string, opts: { project?: string; pi?: boolean } = {}): InitChange[] {
  const project = opts.project || basename(root) || 'project';
  const changes: InitChange[] = [];

  // 1. Empty brain — NEVER clobber an existing one.
  const brainDir = join(root, '.vfkb');
  const entries = join(brainDir, 'entries.jsonl');
  if (!existsSync(entries)) {
    mkdirSync(brainDir, { recursive: true });
    writeFileSync(entries, '');
    changes.push({ path: '.vfkb/entries.jsonl', action: 'created' });
  } else {
    changes.push({ path: '.vfkb/entries.jsonl', action: 'skipped' });
  }

  // 1b. Brain↔engine version stamp (FR-4) — committed, engine-written.
  changes.push({ path: '.vfkb/manifest.json', action: writeManifest(brainDir) });

  // 1c. The committed bootstrap entry-point (ADR-0031) — write if absent or stale.
  {
    const binDir = join(brainDir, 'bin');
    const path = join(binDir, 'bootstrap.mjs');
    const existed = existsSync(path);
    const same = existed && readFileSync(path, 'utf8') === BOOTSTRAP_SRC;
    if (same) {
      changes.push({ path: BOOTSTRAP_REL, action: 'skipped' });
    } else {
      mkdirSync(binDir, { recursive: true });
      writeFileSync(path, BOOTSTRAP_SRC);
      changes.push({ path: BOOTSTRAP_REL, action: existed ? 'updated' : 'created' });
    }
  }

  // 2. .mcp.json — register the vfkb MCP server (merge, keep other servers).
  {
    const path = join(root, '.mcp.json');
    const existed = existsSync(path);
    const cfg = readJson(path) ?? {};
    cfg.mcpServers = cfg.mcpServers ?? {};
    const desired = mcpConfig(project);
    const same = JSON.stringify(cfg.mcpServers.vfkb) === JSON.stringify(desired);
    if (same) {
      changes.push({ path: '.mcp.json', action: 'skipped' });
    } else {
      cfg.mcpServers.vfkb = desired;
      writeJson(path, cfg);
      changes.push({ path: '.mcp.json', action: existed ? 'updated' : 'created' });
    }
  }

  // 3. .claude/settings.json — the four hooks (merge per-event; don't duplicate).
  // Drop any pre-existing vfkb entry and re-append the current form: this UPGRADES an
  // older CWD-relative hook to the anchored one (issue #22) while keeping user hooks.
  {
    const dir = join(root, '.claude');
    const path = join(dir, 'settings.json');
    const existed = existsSync(path);
    const cfg = readJson(path) ?? {};
    cfg.hooks = cfg.hooks ?? {};
    const want = settingsHooks(project);
    let touched = false;
    for (const event of Object.keys(want) as (keyof typeof want)[]) {
      const raw = cfg.hooks[event];
      const cur = Array.isArray(raw) ? raw : raw ? [raw] : [];
      const others = cur.filter((e) => !eventHasVfkb(e)); // keep non-vfkb (user) hooks
      const desired = [...others, ...want[event]];
      if (JSON.stringify(cur) === JSON.stringify(desired)) continue; // already current form
      cfg.hooks[event] = desired;
      touched = true;
    }
    if (touched) {
      mkdirSync(dir, { recursive: true });
      writeJson(path, cfg);
      changes.push({ path: '.claude/settings.json', action: existed ? 'updated' : 'created' });
    } else {
      changes.push({ path: '.claude/settings.json', action: 'skipped' });
    }
  }

  // 4. .gitignore — the derived/operational stanza (append once).
  {
    const path = join(root, '.gitignore');
    // Every derived/operational path. `.lock` is the ADR-0040 concurrency lock:
    // transient, but a `git add .vfkb` timed against a concurrent write would
    // commit it. Keep in step with vfkb's own .gitignore — a consumer whose
    // ignore set is narrower than the engine's is a sweep waiting to happen
    // (one ran across 10 repos on 2026-07-18 for exactly this).
    const lines = [
      '.vfkb/index-meta.json',
      '.vfkb/.sessions/',
      '.vfkb/.signals/',
      '.vfkb/.journal/',
      '.vfkb/.lock',
      '.vfkb/.write-probe-*',
      // Derived per-machine MCP config the pi package writes (absolute paths inside).
      '.vfkb/.pi-mcp.json',
      // pi clones the vfkb package (plus its node_modules) into the PROJECT when the
      // package entry is project-scoped. Derived, multi-hundred-KB, and re-fetched on
      // demand — never commit it. Without this line a consumer's `git status` fills
      // with a vendored clone the moment they first start pi.
      '.pi/git/',
    ];
    // The header the stanza should carry. The OLD one claimed "only
    // .vfkb/entries.jsonl is committed", which is FALSE — manifest.json is
    // committed by design (ADR-0030, the brain↔engine stamp, distinct from the
    // derived index-meta.json). That sentence caused a real defect: the natural
    // response to an untracked manifest.json is to gitignore it, and one
    // consumer ended up with no engine stamp at all.
    const HEADER = [
      '# vfkb — entries.jsonl + manifest.json (the ADR-0030 engine stamp) are committed;',
      '# the vfkb paths below are derived/operational and stay out of git',
    ];
    // Any header this generator has ever emitted, so an upgrade HEALS the stanza
    // in place. Appending a corrected block while leaving the old one alone left
    // the false claim intact AND first in the file, contradicted by a second
    // stanza below it — worse than not fixing it (review of PR #219, blocking 1).
    const STALE_HEADER = /^#\s*vfkb\s*—\s*derived\/operational \(only \.vfkb\/entries\.jsonl is committed\)\s*$/;

    const existed = existsSync(path);
    const cur = existed ? readFileSync(path, 'utf8') : '';
    const curLines = cur.split(/\r?\n/);
    const missing = lines.filter((l) => !curLines.includes(l));
    const staleAt = curLines.findIndex((l) => STALE_HEADER.test(l));

    if (missing.length === 0 && staleAt === -1) {
      changes.push({ path: '.gitignore', action: 'skipped' });
    } else if (staleAt !== -1) {
      // Heal: swap the stale header for the correct one and fold any missing
      // paths into THAT stanza, so the file ends up with exactly one.
      const out = [...curLines];
      out.splice(staleAt, 1, ...HEADER);
      let last = staleAt + HEADER.length - 1;
      for (let i = last + 1; i < out.length && /^\.vfkb\//.test(out[i].trim()); i++) last = i;
      out.splice(last + 1, 0, ...missing);
      writeFileSync(path, out.join('\n'));
      changes.push({ path: '.gitignore', action: 'updated' });
    } else {
      const prefix = cur && !cur.endsWith('\n') ? '\n' : '';
      const block = `${prefix}${cur ? '\n' : ''}${HEADER.join('\n')}\n${missing.join('\n')}\n`;
      writeFileSync(path, cur + block);
      changes.push({ path: '.gitignore', action: existed ? 'updated' : 'created' });
    }
  }

  // 4b. .gitattributes — merge=union for the append-only brain (ADR-0041), so
  // parallel branches that both appended entries union-merge instead of conflicting.
  // Append once; never touches the consumer's other attributes. (GitHub's server-side
  // merge ignores it — a local `git merge` remains the documented fallback, ADR-0041.)
  {
    const path = join(root, '.gitattributes');
    const line = '.vfkb/entries.jsonl merge=union';
    const existed = existsSync(path);
    const cur = existed ? readFileSync(path, 'utf8') : '';
    if (cur.split(/\r?\n/).includes(line)) {
      changes.push({ path: '.gitattributes', action: 'skipped' });
    } else {
      const prefix = cur && !cur.endsWith('\n') ? '\n' : '';
      const block = `${prefix}${cur ? '\n' : ''}# vfkb — the append-only brain unions across branches (ADR-0041)\n${line}\n`;
      writeFileSync(path, cur + block);
      changes.push({ path: '.gitattributes', action: existed ? 'updated' : 'created' });
    }
  }

  // 4c. .pi/settings.json — load the vfkb pi package (ADR-0066 §1/§2). Skippable:
  // wiring pi makes it clone+install the package at startup, which a Claude-only
  // consumer may reasonably decline (`vfkb init --no-pi`).
  if (opts.pi !== false)
  // Project scope is deliberate: it is team-shareable and pi auto-installs missing
  // packages at startup, so a teammate's clone wires itself. Merge, never clobber:
  // keep the consumer's other packages and every other setting.
  //
  // NOTE the ordering contract this relies on: the package's OWN manifest lists the
  // wrapper before the bridge, and pi honours manifest array order (verified 0.73.1 —
  // reversing the manifest reverses what the later extension observes). Consumers do
  // not control that order and must not need to.
  {
    const dir = join(root, '.pi');
    const path = join(dir, 'settings.json');
    const existed = existsSync(path);
    const cfg = readJson(path) ?? {};
    const cur: unknown[] = Array.isArray(cfg.packages) ? cfg.packages : [];
    const has = cur.some((p) =>
      typeof p === 'string'
        ? p === PI_PACKAGE_SOURCE
        : !!p && typeof p === 'object' && (p as { source?: unknown }).source === PI_PACKAGE_SOURCE,
    );
    if (has) {
      changes.push({ path: '.pi/settings.json', action: 'skipped' });
    } else {
      cfg.packages = [...cur, PI_PACKAGE_SOURCE];
      mkdirSync(dir, { recursive: true });
      writeJson(path, cfg);
      changes.push({ path: '.pi/settings.json', action: existed ? 'updated' : 'created' });
    }
  }

  // 5. AGENTS.md — the parameterized "how we track work HERE" snippet (append once).
  {
    const path = join(root, 'AGENTS.md');
    const existed = existsSync(path);
    const cur = existed ? readFileSync(path, 'utf8') : '';
    if (cur.includes(AGENTS_MARKER)) {
      changes.push({ path: 'AGENTS.md', action: 'skipped' });
    } else {
      const sep = cur && !cur.endsWith('\n') ? '\n\n' : cur ? '\n' : '';
      writeFileSync(path, cur + sep + agentsSnippet(project));
      changes.push({ path: 'AGENTS.md', action: existed ? 'updated' : 'created' });
    }
  }

  return changes;
}

// The one step init cannot do for you (printed by the CLI).
export function approvalNotice(project: string): string {
  return [
    `vfkb wired for project "${project}".`,
    '',
    'Next (one-time, manual):',
    '  1. Set $VFKB_BUNDLE_DIR once per machine to the vfkb bundles dir, e.g.:',
    '       export VFKB_BUNDLE_DIR=/path/to/vfkb/dist/bundles   # (run `npm run build:bundles` in the vfkb repo)',
    '  2. Start `claude` in this repo and APPROVE the project MCP server + hooks when prompted (once).',
    '  3. Commit the wiring + the empty brain: git add .mcp.json .claude .gitignore .gitattributes .vfkb AGENTS.md',
  ].join('\n');
}
